/**:
  ros__parameters:
    name: 'Robot3'
    type: 'ISR_M2'
    goal:
      x: 13.3
      y: 7.7
      theta: -1.57079632679
    # Optional: Gazebo Initial Spwan Pose
    spawn:
      x: 17.9
      y: 12.5
      theta: -1.57079632679