/**:
  ros__parameters:
    name: 'Robot1'
    type: 'ISR_M2'
    goal:
      x: 15.6
      y: 6.3
      theta: 0.0
    # Optional: Gazebo Initial Spwan Pose
    spawn:
      x: 10.2
      y: 6.3
      theta: 0.0