/**:
  ros__parameters:
    ISR_M2:
      size: 0.70

      wheels:
        separation: 0.5
        radius: 0.32

      linear:
        velocity: 0.4
        acceleration: 0.5
        tolerance: 0.10

      angular:
        velocity: 0.4
        acceleration: 0.5
        tolerance: 0.018

      controlParam:
        kanayama:
          Kx: 0.25
          Ky: 1.00
          Ktheta: 1.27
        PID:
          kp_linear: 0.75
          kd_linear: 0.15
          kp_angular: 0.75
          kd_angular: 0.15

      odometry:
        frame_id: "odom"
        child_frame_id: "base_link"